version: '3'

services:
  nano-node:
    image: nanocurrency/nano:latest
    container_name: nano-node
    hostname: nano-node
    environment:
      - TERM=xterm
    restart: unless-stopped
    ports:
      - "7075:7075/udp"
      - "7075:7075"
      - "127.0.0.1:7076:7076"
    volumes:
      - nano-node-logs:/root/RaiBlocks/log
      - ./nano-node:/root/RaiBlocks

  nano-node-monitor:
    image: nanotools/nanonodemonitor
    container_name: nano-node-monitor
    hostname: nano-node-monitor
    restart: unless-stopped
    volumes:
      - ./nano-node-monitor:/opt/nanoNodeMonitor
    ports:
      - "80:80"

  nano-node-watchdog:
    build: ./nano-node-watchdog/ 
    image: nano-node-docker-stack/nano-node-watchdog
    container_name: nano-node-watchdog
    hostname: nano-node-watcher
    restart: unless-stopped
    volumes:
      - nano-node-logs:/opt/nanoNodeLog
      - /var/run/docker.sock:/var/run/docker.sock
      - ./nano-node-watchdog/log:/opt/nanoNodeWatchdog/log

  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:

volumes:
  nano-node-logs: