version: '3'

services:
  nano-node:
    image: nanocurrency/nano:latest
    container_name: nano-node
    hostname: nano-node
    environment:
      - TERM=xterm
    restart: unless-stopped
    ports:
      - "7075:7075/udp"
      - "7075:7075"
      - "127.0.0.1:7076:7076"
    volumes:
      - ./nano-node:/root/RaiBlocks

  nano-node-monitor:
    image: nanotools/nanonodemonitor
    container_name: nano-node-monitor
    hostname: nano-node-monitor
    restart: unless-stopped
    volumes:
      - ./nano-node-monitor:/opt/nanoNodeMonitor
    ports:
      - "80:80"

networks:
  default:
